"""add-indexing status

Revision ID: 243a7473b750
Revises: 951a82befdb3
Create Date: 2026-07-12 01:46:29.316966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '243a7473b750'
down_revision: Union[str, None] = '951a82befdb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('indexing_status', sa.Enum('PENDING', 'INDEXING', 'COMPLETED', 'FAILED', name='repo_indexing_status', native_enum=False, length=20), server_default=sa.text("'PENDING'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo', 'indexing_status')
    # ### end Alembic commands ###
