"""empty message

Revision ID: 51b6db2b00c0
Revises: efc8cecac0b4
Create Date: 2026-07-27 19:28:22.358291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '51b6db2b00c0'
down_revision: Union[str, None] = 'efc8cecac0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('codecomment_pr_id_fkey'), 'codecomment', type_='foreignkey')
    op.create_foreign_key(None, 'codecomment', 'pullrequest', ['pr_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pullrequest_repo_id_fkey'), 'pullrequest', type_='foreignkey')
    op.create_foreign_key(None, 'pullrequest', 'repo', ['repo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reviewsummary_pr_id_fkey'), 'reviewsummary', type_='foreignkey')
    op.create_foreign_key(None, 'reviewsummary', 'pullrequest', ['pr_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviewsummary', type_='foreignkey')
    op.create_foreign_key(op.f('reviewsummary_pr_id_fkey'), 'reviewsummary', 'pullrequest', ['pr_id'], ['id'])
    op.drop_constraint(None, 'pullrequest', type_='foreignkey')
    op.create_foreign_key(op.f('pullrequest_repo_id_fkey'), 'pullrequest', 'repo', ['repo_id'], ['id'])
    op.drop_constraint(None, 'codecomment', type_='foreignkey')
    op.create_foreign_key(op.f('codecomment_pr_id_fkey'), 'codecomment', 'pullrequest', ['pr_id'], ['id'])
    # ### end Alembic commands ###
