"""empty message

Revision ID: 5d1d3894e8a5
Revises: d11be80b25c9
Create Date: 2026-07-14 22:18:02.769933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5d1d3894e8a5'
down_revision: Union[str, None] = 'd11be80b25c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installation_github_installation_id'), table_name='installation')
    op.create_index(op.f('ix_installation_github_installation_id'), 'installation', ['github_installation_id'], unique=True)
    op.drop_constraint(op.f('installation_repo_id_fkey'), 'installation', type_='foreignkey')
    op.drop_column('installation', 'repo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installation', sa.Column('repo_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('installation_repo_id_fkey'), 'installation', 'repo', ['repo_id'], ['id'])
    op.drop_index(op.f('ix_installation_github_installation_id'), table_name='installation')
    op.create_index(op.f('ix_installation_github_installation_id'), 'installation', ['github_installation_id'], unique=False)
    # ### end Alembic commands ###
