"""empty message

Revision ID: 621a1ccb8937
Revises: 69728c9d71d0
Create Date: 2026-09-05 15:12:21.231382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '621a1ccb8937'
down_revision: Union[str, None] = '69728c9d71d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codecomment', sa.Column('github_review_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codecomment', 'github_review_id')
    # ### end Alembic commands ###
