"""empty message

Revision ID: 69728c9d71d0
Revises: 86d7ae9f650b
Create Date: 2026-08-30 00:39:29.224249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '69728c9d71d0'
down_revision: Union[str, None] = '86d7ae9f650b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('llm_client', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'llm_client')
    # ### end Alembic commands ###
