"""add llm config and review usages

Revision ID: 6f386ff6d9a4
Revises: 51b6db2b00c0
Create Date: 2026-07-31 22:21:52.502161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f386ff6d9a4'
down_revision: Union[str, None] = '51b6db2b00c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llmconfigrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llmconfigrecord_user_id'), 'llmconfigrecord', ['user_id'], unique=False)
    op.create_table('reviewusage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pr_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review_summary_id', sa.Uuid(), nullable=True),
    sa.Column('review_status', sa.Enum('SUCCESS', 'FAILED', name='reviewrunstatus'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('input_token_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pullrequest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_summary_id'], ['reviewsummary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewusage_user_id'), 'reviewusage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewusage_user_id'), table_name='reviewusage')
    op.drop_table('reviewusage')
    op.drop_index(op.f('ix_llmconfigrecord_user_id'), table_name='llmconfigrecord')
    op.drop_table('llmconfigrecord')
    # ### end Alembic commands ###
