"""empty message

Revision ID: 86d7ae9f650b
Revises: dc8dcc7ea22e
Create Date: 2026-08-20 00:40:40.583112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '86d7ae9f650b'
down_revision: Union[str, None] = 'dc8dcc7ea22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codecomment', sa.Column('review_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_codecomment_review_id'), 'codecomment', ['review_id'], unique=False)
    op.create_foreign_key(None, 'codecomment', 'review', ['review_id'], ['id'], ondelete='CASCADE')
    op.add_column('review', sa.Column('github_review_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('reviewsummary', sa.Column('review_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'reviewsummary', ['review_id'])
    op.create_foreign_key(None, 'reviewsummary', 'review', ['review_id'], ['id'], ondelete='CASCADE')
    op.add_column('reviewusage', sa.Column('review_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_reviewusage_review_id'), 'reviewusage', ['review_id'], unique=False)
    op.create_foreign_key(None, 'reviewusage', 'review', ['review_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviewusage', type_='foreignkey')
    op.drop_index(op.f('ix_reviewusage_review_id'), table_name='reviewusage')
    op.drop_column('reviewusage', 'review_id')
    op.drop_constraint(None, 'reviewsummary', type_='foreignkey')
    op.drop_constraint(None, 'reviewsummary', type_='unique')
    op.drop_column('reviewsummary', 'review_id')
    op.drop_column('review', 'github_review_id')
    op.drop_constraint(None, 'codecomment', type_='foreignkey')
    op.drop_index(op.f('ix_codecomment_review_id'), table_name='codecomment')
    op.drop_column('codecomment', 'review_id')
    # ### end Alembic commands ###
