"""sandbox provider id add

Revision ID: 951a82befdb3
Revises: d2c05e88f8e9
Create Date: 2026-07-07 05:11:26.987098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '951a82befdb3'
down_revision: Union[str, None] = 'd2c05e88f8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandbox', sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('sandbox', 'daytona_sandbox_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandbox', sa.Column('daytona_sandbox_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sandbox', 'provider_id')
    # ### end Alembic commands ###
