"""empty message

Revision ID: 98d1bc3c5752
Revises: a34346e4a964
Create Date: 2026-08-13 04:03:52.168564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '98d1bc3c5752'
down_revision: Union[str, None] = 'a34346e4a964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('is_indexed', sa.Boolean(), nullable=True))
    op.add_column('repo', sa.Column('indexed_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo', 'indexed_run_id')
    op.drop_column('repo', 'is_indexed')
    # ### end Alembic commands ###
