"""drop indexrun table and repo index columns

Revision ID: a0ca2a72f016
Revises: 621a1ccb8937
Create Date: 2026-09-26 15:28:08.218849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0ca2a72f016'
down_revision: Union[str, None] = '621a1ccb8937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexrun_state'), table_name='indexrun')
    op.drop_index(op.f('ix_indexrun_user_id'), table_name='indexrun')
    op.drop_index(op.f('ix_indexrun_workflow_id'), table_name='indexrun')
    op.drop_table('indexrun')
    op.drop_column('repo', 'is_indexed')
    op.drop_column('repo', 'indexed_run_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('indexed_run_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('repo', sa.Column('is_indexed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('indexrun',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('repo_owner', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('repo_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('repo_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('default_branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('chunk_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sandbox_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('s3_bucket', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('indexrun_pkey'))
    )
    op.create_index(op.f('ix_indexrun_workflow_id'), 'indexrun', ['workflow_id'], unique=True)
    op.create_index(op.f('ix_indexrun_user_id'), 'indexrun', ['user_id'], unique=False)
    op.create_index(op.f('ix_indexrun_state'), 'indexrun', ['state'], unique=False)
    # ### end Alembic commands ###
