"""empty message

Revision ID: a34346e4a964
Revises: fd84562ca886
Create Date: 2026-08-12 10:16:41.893181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a34346e4a964'
down_revision: Union[str, None] = 'fd84562ca886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexrun',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('error_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sandbox_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('s3_bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexrun_state'), 'indexrun', ['state'], unique=False)
    op.create_index(op.f('ix_indexrun_user_id'), 'indexrun', ['user_id'], unique=False)
    op.create_index(op.f('ix_indexrun_workflow_id'), 'indexrun', ['workflow_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexrun_workflow_id'), table_name='indexrun')
    op.drop_index(op.f('ix_indexrun_user_id'), table_name='indexrun')
    op.drop_index(op.f('ix_indexrun_state'), table_name='indexrun')
    op.drop_table('indexrun')
    # ### end Alembic commands ###
