"""empty message

Revision ID: d11be80b25c9
Revises: 243a7473b750
Create Date: 2026-07-13 19:58:47.157570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd11be80b25c9'
down_revision: Union[str, None] = '243a7473b750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('github_installation_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_login', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('repository_selection', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('suspended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_github_installation_id'), 'installation', ['github_installation_id'], unique=False)
    op.create_index(op.f('ix_installation_user_id'), 'installation', ['user_id'], unique=False)
    op.add_column('repo', sa.Column('github_repo_id', sa.Integer(), nullable=False))
    op.add_column('repo', sa.Column('clone_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False))
    op.create_unique_constraint(None, 'repo', ['github_repo_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repo', type_='unique')
    op.drop_column('repo', 'clone_url')
    op.drop_column('repo', 'github_repo_id')
    op.drop_index(op.f('ix_installation_user_id'), table_name='installation')
    op.drop_index(op.f('ix_installation_github_installation_id'), table_name='installation')
    op.drop_table('installation')
    # ### end Alembic commands ###
