"""drop commit_snapshots and fix FKs

Revision ID: d2c05e88f8e9
Revises: 0002_extend_repos_and_sandboxes
Create Date: 2026-07-05 08:40:30.949963

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2c05e88f8e9"
down_revision: Union[str, None] = "0002_extend_repos_and_sandboxes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repo",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("repo_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_owner", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("default_branch", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_repo_user_id"), "repo", ["user_id"], unique=False)
    op.create_table(
        "pullrequest",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OPEN", "CLOSED", "MERGED", name="prstatus"),
            nullable=False,
        ),
        sa.Column("base_branch", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("head_branch", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("head_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sandbox",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sandbox_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "STARTED",
                "PAUSED",
                "STOPPED",
                "DELETED",
                "ARCHIVED",
                name="sandboxstate",
            ),
            nullable=False,
        ),
        sa.Column(
            "daytona_sandbox_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("stopped_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["repo_id"], ["repo.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "codecomment",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pr_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("commit_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "github_comment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("P1_CRITICAL", "P2_WARNING", "P3_NITPICK", name="commentseverity"),
            nullable=False,
        ),
        sa.Column("from_line", sa.Integer(), nullable=False),
        sa.Column("to_line", sa.Integer(), nullable=False),
        sa.Column("side", sa.Enum("RIGHT", "LEFT", name="commentside"), nullable=False),
        sa.Column("node_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("ACTIVE", "OUTDATED", "RESOLVED", name="commentstate"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pr_id"],
            ["pullrequest.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reviewsummary",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pr_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("commit_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "github_review_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum("APPROVE", "COMMENT", "REQUEST_CHANGES", name="reviewverdict"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pr_id"],
            ["pullrequest.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_commit_snapshots_pr_id"), table_name="commit_snapshots")
    # op.drop_table("commit_snapshots")
    op.execute("DROP TABLE commit_snapshots CASCADE")
    op.drop_index(
        op.f("ix_code_comments_commit_file_state"), table_name="code_comments"
    )
    op.drop_index(op.f("ix_code_comments_commit_id"), table_name="code_comments")
    op.drop_index(op.f("ix_code_comments_pr_id"), table_name="code_comments")
    op.drop_table("code_comments")
    op.drop_index(op.f("ix_review_summaries_pr_id"), table_name="review_summaries")
    op.drop_table("review_summaries")
    op.drop_index(op.f("ix_pull_requests_repo_id"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_status"), table_name="pull_requests")
    op.drop_table("pull_requests")
    op.drop_index(op.f("ix_sandboxes_repo_id"), table_name="sandboxes")
    op.drop_index(op.f("ix_sandboxes_state"), table_name="sandboxes")
    op.drop_index(op.f("ix_sandboxes_user_id"), table_name="sandboxes")
    op.drop_index(op.f("ix_sandboxes_user_repo_state"), table_name="sandboxes")
    op.drop_table("sandboxes")
    op.drop_index(op.f("ix_repos_org_id"), table_name="repos")
    op.drop_index(op.f("ix_repos_user_id"), table_name="repos")
    op.drop_table("repos")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repos",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column("org_id", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.Column("github_repo_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "repo_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "repo_owner", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "clone_url", sa.VARCHAR(length=1024), autoincrement=False, nullable=False
        ),
        sa.Column(
            "github_installation_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column(
            "html_url", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
        sa.Column(
            "private",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "default_branch", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("repos_pkey")),
        sa.UniqueConstraint(
            "github_repo_id",
            name=op.f("uq_repos_github_repo_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "repo_owner",
            "repo_name",
            name=op.f("uq_repos_owner_name"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_repos_user_id"), "repos", ["user_id"], unique=False)
    op.create_index(op.f("ix_repos_org_id"), "repos", ["org_id"], unique=False)
    op.create_table(
        "sandboxes",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column("repo_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "sandbox_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "state",
            sa.VARCHAR(length=16),
            server_default=sa.text("'STARTED'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "daytona_sandbox_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "stopped_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "state::text = ANY (ARRAY['STARTED'::character varying, 'PAUSED'::character varying, 'STOPPED'::character varying, 'DELETED'::character varying, 'ARCHIVED'::character varying]::text[])",
            name=op.f("ck_sandboxes_state"),
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repos.id"],
            name=op.f("sandboxes_repo_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sandboxes_pkey")),
    )
    op.create_index(
        op.f("ix_sandboxes_user_repo_state"),
        "sandboxes",
        ["user_id", "repo_id", "state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sandboxes_user_id"), "sandboxes", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_sandboxes_state"), "sandboxes", ["state"], unique=False)
    op.create_index(
        op.f("ix_sandboxes_repo_id"), "sandboxes", ["repo_id"], unique=False
    )
    op.create_table(
        "pull_requests",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("repo_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("github_pr_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "author", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "title", sa.VARCHAR(length=1024), autoincrement=False, nullable=False
        ),
        sa.Column("body", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            sa.VARCHAR(length=16),
            server_default=sa.text("'OPEN'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "base_branch", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "base_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "head_branch", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "status::text = ANY (ARRAY['OPEN'::character varying, 'CLOSED'::character varying, 'MERGED'::character varying]::text[])",
            name=op.f("ck_pull_requests_status"),
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repos.id"],
            name=op.f("pull_requests_repo_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pull_requests_pkey")),
        sa.UniqueConstraint(
            "github_pr_id",
            name=op.f("uq_pull_requests_github_pr_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "repo_id",
            "number",
            name=op.f("uq_pull_requests_repo_id_number"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_pull_requests_status"), "pull_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_pull_requests_repo_id"), "pull_requests", ["repo_id"], unique=False
    )
    op.create_table(
        "review_summaries",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("pr_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("commit_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("github_review_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "verdict", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict::text = ANY (ARRAY['APPROVE'::character varying, 'COMMENT'::character varying, 'REQUEST_CHANGES'::character varying]::text[])",
            name=op.f("ck_review_summaries_verdict"),
        ),
        sa.ForeignKeyConstraint(
            ["commit_id"],
            ["commit_snapshots.id"],
            name=op.f("review_summaries_commit_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pr_id"],
            ["pull_requests.id"],
            name=op.f("review_summaries_pr_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("review_summaries_pkey")),
        sa.UniqueConstraint(
            "commit_id",
            name=op.f("uq_review_summaries_commit_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_review_summaries_pr_id"), "review_summaries", ["pr_id"], unique=False
    )
    op.create_table(
        "code_comments",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("pr_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("commit_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("github_comment_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "file_name", sa.VARCHAR(length=1024), autoincrement=False, nullable=False
        ),
        sa.Column("comment", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "severity", sa.VARCHAR(length=16), autoincrement=False, nullable=False
        ),
        sa.Column("from_line", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("to_line", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "side",
            sa.VARCHAR(length=8),
            server_default=sa.text("'RIGHT'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "node_type", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
        sa.Column(
            "state",
            sa.VARCHAR(length=16),
            server_default=sa.text("'ACTIVE'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity::text = ANY (ARRAY['P1_CRITICAL'::character varying, 'P2_WARNING'::character varying, 'P3_NITPICK'::character varying]::text[])",
            name=op.f("ck_code_comments_severity"),
        ),
        sa.CheckConstraint(
            "side::text = ANY (ARRAY['RIGHT'::character varying, 'LEFT'::character varying]::text[])",
            name=op.f("ck_code_comments_side"),
        ),
        sa.CheckConstraint(
            "state::text = ANY (ARRAY['ACTIVE'::character varying, 'OUTDATED'::character varying, 'RESOLVED'::character varying]::text[])",
            name=op.f("ck_code_comments_state"),
        ),
        sa.ForeignKeyConstraint(
            ["commit_id"],
            ["commit_snapshots.id"],
            name=op.f("code_comments_commit_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pr_id"],
            ["pull_requests.id"],
            name=op.f("code_comments_pr_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("code_comments_pkey")),
    )
    op.create_index(
        op.f("ix_code_comments_pr_id"), "code_comments", ["pr_id"], unique=False
    )
    op.create_index(
        op.f("ix_code_comments_commit_id"), "code_comments", ["commit_id"], unique=False
    )
    op.create_index(
        op.f("ix_code_comments_commit_file_state"),
        "code_comments",
        ["commit_id", "file_name", "state"],
        unique=False,
    )
    op.create_table(
        "commit_snapshots",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("pr_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "previous_reviewed_sha",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "analysis_status",
            sa.VARCHAR(length=16),
            server_default=sa.text("'PENDING'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "analysis_status::text = ANY (ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying]::text[])",
            name=op.f("ck_commit_snapshots_analysis_status"),
        ),
        sa.ForeignKeyConstraint(
            ["pr_id"],
            ["pull_requests.id"],
            name=op.f("commit_snapshots_pr_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("commit_snapshots_pkey")),
        sa.UniqueConstraint(
            "pr_id",
            "sha",
            name=op.f("uq_commit_snapshots_pr_id_sha"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_commit_snapshots_pr_id"), "commit_snapshots", ["pr_id"], unique=False
    )
    op.drop_table("reviewsummary")
    op.drop_table("codecomment")
    op.drop_table("sandbox")
    op.drop_table("pullrequest")
    op.drop_index(op.f("ix_repo_user_id"), table_name="repo")
    op.drop_table("repo")
    # ### end Alembic commands ###
