"""empty message

Revision ID: dc8dcc7ea22e
Revises: ec54a29f7fe5
Create Date: 2026-08-19 20:11:16.861740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc8dcc7ea22e'
down_revision: Union[str, None] = 'ec54a29f7fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gh_repo_id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('commit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('error_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sandbox_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pullrequest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_commit_id'), 'review', ['commit_id'], unique=False)
    op.create_index(op.f('ix_review_pr_id'), 'review', ['pr_id'], unique=False)
    op.create_index(op.f('ix_review_repo_id'), 'review', ['repo_id'], unique=False)
    op.create_index(op.f('ix_review_state'), 'review', ['state'], unique=False)
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_workflow_id'), 'review', ['workflow_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_workflow_id'), table_name='review')
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_index(op.f('ix_review_state'), table_name='review')
    op.drop_index(op.f('ix_review_repo_id'), table_name='review')
    op.drop_index(op.f('ix_review_pr_id'), table_name='review')
    op.drop_index(op.f('ix_review_commit_id'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
