"""empty message

Revision ID: ec54a29f7fe5
Revises: 98d1bc3c5752
Create Date: 2026-08-18 00:51:08.657191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ec54a29f7fe5'
down_revision: Union[str, None] = '98d1bc3c5752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewusage', sa.Column('llm_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('reviewusage', sa.Column('llm_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('reviewusage', sa.Column('llm_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviewusage', 'llm_base_url')
    op.drop_column('reviewusage', 'llm_provider')
    op.drop_column('reviewusage', 'llm_model_id')
    # ### end Alembic commands ###
