"""empty message

Revision ID: efc8cecac0b4
Revises: fb1f0819aade
Create Date: 2026-07-16 02:59:06.046298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efc8cecac0b4'
down_revision: Union[str, None] = 'fb1f0819aade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reposetupresult',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('ecosystem', sa.String(length=16), nullable=False),
    sa.Column('manager', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('install_cmd', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('bootstrapped_tools', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('llm_provider', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('sandbox_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reposetupresult_user_id'), 'reposetupresult', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reposetupresult_user_id'), table_name='reposetupresult')
    op.drop_table('reposetupresult')
    # ### end Alembic commands ###
