"""empty message

Revision ID: fb1f0819aade
Revises: 5d1d3894e8a5
Create Date: 2026-07-15 18:11:55.933443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fb1f0819aade'
down_revision: Union[str, None] = '5d1d3894e8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('isSetup', sa.Boolean(), nullable=False))
    op.drop_column('repo', 'indexing_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('indexing_status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('repo', 'isSetup')
    # ### end Alembic commands ###
