/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardRepositoriesRouteRouteImport } from './routes/dashboard/repositories/route'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardSearchOwnerNameRouteRouteImport } from './routes/dashboard/search/$owner/$name/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRepositoriesRouteRoute =
  DashboardRepositoriesRouteRouteImport.update({
    id: '/repositories',
    path: '/repositories',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSearchOwnerNameRouteRoute =
  DashboardSearchOwnerNameRouteRouteImport.update({
    id: '/search/$owner/$name',
    path: '/search/$owner/$name',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/repositories': typeof DashboardRepositoriesRouteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/search/$owner/$name': typeof DashboardSearchOwnerNameRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/repositories': typeof DashboardRepositoriesRouteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/search/$owner/$name': typeof DashboardSearchOwnerNameRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/repositories': typeof DashboardRepositoriesRouteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/search/$owner/$name': typeof DashboardSearchOwnerNameRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/repositories'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/search/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/repositories'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/search/$owner/$name'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/repositories'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/search/$owner/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/repositories': {
      id: '/dashboard/repositories'
      path: '/repositories'
      fullPath: '/dashboard/repositories'
      preLoaderRoute: typeof DashboardRepositoriesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/search/$owner/$name': {
      id: '/dashboard/search/$owner/$name'
      path: '/search/$owner/$name'
      fullPath: '/dashboard/search/$owner/$name'
      preLoaderRoute: typeof DashboardSearchOwnerNameRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardRepositoriesRouteRoute: typeof DashboardRepositoriesRouteRoute
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSearchOwnerNameRouteRoute: typeof DashboardSearchOwnerNameRouteRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardRepositoriesRouteRoute: DashboardRepositoriesRouteRoute,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSearchOwnerNameRouteRoute: DashboardSearchOwnerNameRouteRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
